--
-- hull.build — Build a standalone hull application binary
--
-- Usage: hull build [options] [app_dir]
--   --runtime lua|js|both  Runtime to include (default: lua)
--   --sign <key_file>      Sign with Ed25519 private key
--   --cc <compiler>        C compiler to use (default: cosmocc)
--   --output <path>        Output binary path (default: app_dir/app)
--
-- SPDX-License-Identifier: AGPL-3.0-or-later
--

local json = require("hull.json")

-- ── Argument parsing ─────────────────────────────────────────────────

local function parse_args()
    local opts = {
        runtime = "lua",
        sign = nil,
        cc = nil,         -- resolved from tool.cc (set by C, default cosmocc)
        output = nil,
        app_dir = ".",
    }

    local i = 1
    while i <= #arg do
        local a = arg[i]
        if a == "--runtime" then
            i = i + 1
            opts.runtime = arg[i]
        elseif a == "--sign" then
            i = i + 1
            opts.sign = arg[i]
        elseif a == "--cc" then
            i = i + 1
            opts.cc = arg[i]
        elseif a == "--output" or a == "-o" then
            i = i + 1
            opts.output = arg[i]
        elseif a:sub(1, 1) ~= "-" then
            opts.app_dir = a
        end
        i = i + 1
    end

    if not opts.output then
        opts.output = opts.app_dir .. "/app"
    end

    return opts
end

-- ── File utilities ───────────────────────────────────────────────────

local function read_file(path)
    return tool.read_file(path)
end

local function write_file(path, data)
    return tool.write_file(path, data)
end

local function file_exists(path)
    return tool.file_exists(path)
end

-- List .lua files recursively in a directory (using tool.find_files)
local function find_lua_files(dir)
    return tool.find_files(dir, "*.lua")
end

-- List .html files recursively in a directory
local function find_html_files(dir)
    return tool.find_files(dir, "*.html")
end

-- List all files recursively in a directory
local function find_all_files(dir)
    return tool.find_files(dir, "*")
end

-- List .sql files in a directory (non-recursive, sorted)
local function find_sql_files(dir)
    local files = tool.find_files(dir, "*.sql")
    table.sort(files)
    return files
end

-- ── xxd in Lua ───────────────────────────────────────────────────────

local function xxd_data(varname, data)
    local lines = {}
    lines[#lines + 1] = "static const unsigned char " .. varname .. "[] = {"
    for i = 1, #data, 12 do
        local chunk = {}
        for j = i, math.min(i + 11, #data) do
            chunk[#chunk + 1] = string.format("0x%02x", data:byte(j))
        end
        lines[#lines + 1] = "  " .. table.concat(chunk, ", ") .. ","
    end
    lines[#lines + 1] = "};"
    return table.concat(lines, "\n")
end

-- ── Build steps ──────────────────────────────────────────────────────

local function generate_app_registry(app_dir, lua_files)
    local parts = {}
    local entries = {}

    parts[#parts + 1] = "/* Auto-generated by hull build — do not edit */"
    parts[#parts + 1] = ""

    for _, path in ipairs(lua_files) do
        local data = read_file(path)
        if not data then
            tool.stderr("hull build: cannot read " .. path .. "\n")
            tool.exit(1)
        end

        -- Relative path from app_dir
        local rel = path:sub(#app_dir + 2) -- strip "dir/"
        local modname = "./" .. rel:gsub("%.lua$", "")
        local varname = "app_" .. rel:gsub("[/.]", "_")

        parts[#parts + 1] = xxd_data(varname, data)
        parts[#parts + 1] = ""

        entries[#entries + 1] = string.format(
            '    { "%s", %s, sizeof(%s) },', modname, varname, varname)
    end

    parts[#parts + 1] = "typedef struct { const char *name; const unsigned char *data; unsigned int len; } HlStdlibEntry;"
    parts[#parts + 1] = "const HlStdlibEntry hl_app_lua_entries[] = {"
    for _, e in ipairs(entries) do
        parts[#parts + 1] = e
    end
    parts[#parts + 1] = "    { 0, 0, 0 }"
    parts[#parts + 1] = "};"

    return table.concat(parts, "\n")
end

local function generate_template_registry(app_dir, html_files)
    local parts = {}
    local entries = {}

    parts[#parts + 1] = "/* Auto-generated template entries by hull build — do not edit */"
    parts[#parts + 1] = ""

    local templates_dir = app_dir .. "/templates/"
    local templates_dir_len = #templates_dir

    for _, path in ipairs(html_files) do
        local data = read_file(path)
        if not data then
            tool.stderr("hull build: cannot read " .. path .. "\n")
            tool.exit(1)
        end

        -- Relative path from templates/ dir (e.g. "pages/home.html", "base.html")
        local rel = path:sub(templates_dir_len + 1)
        local varname = "tpl_" .. rel:gsub("[/.]", "_")

        parts[#parts + 1] = xxd_data(varname, data)
        parts[#parts + 1] = ""

        entries[#entries + 1] = string.format(
            '    { "%s", %s, sizeof(%s) },', rel, varname, varname)
    end

    parts[#parts + 1] = "#ifndef HL_STDLIB_ENTRY_DEFINED"
    parts[#parts + 1] = "#define HL_STDLIB_ENTRY_DEFINED"
    parts[#parts + 1] = "typedef struct { const char *name; const unsigned char *data; unsigned int len; } HlStdlibEntry;"
    parts[#parts + 1] = "#endif"
    parts[#parts + 1] = "const HlStdlibEntry hl_app_template_entries[] = {"
    for _, e in ipairs(entries) do
        parts[#parts + 1] = e
    end
    parts[#parts + 1] = "    { 0, 0, 0 }"
    parts[#parts + 1] = "};"

    return table.concat(parts, "\n")
end

local function generate_static_registry(app_dir, static_files)
    local parts = {}
    local entries = {}

    parts[#parts + 1] = "/* Auto-generated static entries by hull build — do not edit */"
    parts[#parts + 1] = ""

    local static_dir = app_dir .. "/static/"
    local static_dir_len = #static_dir

    for _, path in ipairs(static_files) do
        local data = read_file(path)
        if not data then
            tool.stderr("hull build: cannot read " .. path .. "\n")
            tool.exit(1)
        end

        -- Relative path from static/ dir (e.g. "style.css", "js/app.js")
        local rel = path:sub(static_dir_len + 1)
        local varname = "static_" .. rel:gsub("[/.]", "_")

        parts[#parts + 1] = xxd_data(varname, data)
        parts[#parts + 1] = ""

        entries[#entries + 1] = string.format(
            '    { "%s", %s, sizeof(%s) },', rel, varname, varname)
    end

    parts[#parts + 1] = "#ifndef HL_STDLIB_ENTRY_DEFINED"
    parts[#parts + 1] = "#define HL_STDLIB_ENTRY_DEFINED"
    parts[#parts + 1] = "typedef struct { const char *name; const unsigned char *data; unsigned int len; } HlStdlibEntry;"
    parts[#parts + 1] = "#endif"
    parts[#parts + 1] = "const HlStdlibEntry hl_app_static_entries[] = {"
    for _, e in ipairs(entries) do
        parts[#parts + 1] = e
    end
    parts[#parts + 1] = "    { 0, 0, 0 }"
    parts[#parts + 1] = "};"

    return table.concat(parts, "\n")
end

local function generate_migration_registry(app_dir, sql_files)
    local parts = {}
    local entries = {}

    parts[#parts + 1] = "/* Auto-generated migration entries by hull build — do not edit */"
    parts[#parts + 1] = ""

    local migrations_dir = app_dir .. "/migrations/"
    local migrations_dir_len = #migrations_dir

    for _, path in ipairs(sql_files) do
        local data = read_file(path)
        if not data then
            tool.stderr("hull build: cannot read " .. path .. "\n")
            tool.exit(1)
        end

        -- Relative path from migrations/ dir (e.g. "001_init.sql")
        local rel = path:sub(migrations_dir_len + 1)
        local varname = "migration_" .. rel:gsub("[/.]", "_")

        parts[#parts + 1] = xxd_data(varname, data)
        parts[#parts + 1] = ""

        entries[#entries + 1] = string.format(
            '    { "%s", %s, sizeof(%s) },', rel, varname, varname)
    end

    parts[#parts + 1] = "#ifndef HL_STDLIB_ENTRY_DEFINED"
    parts[#parts + 1] = "#define HL_STDLIB_ENTRY_DEFINED"
    parts[#parts + 1] = "typedef struct { const char *name; const unsigned char *data; unsigned int len; } HlStdlibEntry;"
    parts[#parts + 1] = "#endif"
    parts[#parts + 1] = "const HlStdlibEntry hl_app_migration_entries[] = {"
    for _, e in ipairs(entries) do
        parts[#parts + 1] = e
    end
    parts[#parts + 1] = "    { 0, 0, 0 }"
    parts[#parts + 1] = "};"

    return table.concat(parts, "\n")
end

local function sign_app(app_dir, lua_files, key_file, sign_ctx, migration_files)
    local key_data = read_file(key_file)
    if not key_data then
        tool.stderr("hull build: cannot read key file: " .. key_file .. "\n")
        tool.exit(1)
    end
    local sk_hex = key_data:match("^(%x+)")
    if not sk_hex or #sk_hex ~= 128 then
        tool.stderr("hull build: invalid key file format\n")
        tool.exit(1)
    end

    -- Derive public key
    local pk_file = key_file:gsub("%.key$", ".pub")
    local pk_data = read_file(pk_file)
    local pk_hex = pk_data and pk_data:match("^(%x+)") or ""

    -- Compute file hashes
    local file_hashes = {}
    for _, path in ipairs(lua_files) do
        local data = read_file(path)
        local rel = path:sub(#app_dir + 2)
        file_hashes[rel] = crypto.sha256(data)
    end

    -- Include migration file hashes
    if migration_files then
        for _, path in ipairs(migration_files) do
            local data = read_file(path)
            local rel = path:sub(#app_dir + 2)
            file_hashes[rel] = crypto.sha256(data)
        end
    end

    -- Execute app to capture manifest
    local manifest = nil
    local entry = app_dir .. "/app.lua"
    if file_exists(entry) then
        local chunk = tool.loadfile(entry)
        if chunk then
            pcall(chunk)
            manifest = app.get_manifest()
        end
    end

    -- Read platform.sig (required for --sign)
    local platform = nil
    if sign_ctx.platform_sig_path then
        local psig_data = read_file(sign_ctx.platform_sig_path)
        if psig_data then
            platform = json.decode(psig_data)
        end
    end
    if not platform then
        tool.stderr("hull build: cannot read platform.sig (required for --sign)\n")
        tool.stderr("hint: run `hull sign-platform <key>` first\n")
        tool.exit(1)
    end

    -- Capture compiler version
    local cc_version = nil
    if sign_ctx.cc then
        local ver_out = tool.spawn_read({sign_ctx.cc, "--version"})
        if ver_out then
            cc_version = ver_out:match("^([^\n]+)")
        end
    end

    -- Build the signed payload (canonical JSON key order)
    local payload_table = {
        binary_hash = sign_ctx.binary_hash,
        build = {
            cc = sign_ctx.cc or "cosmocc",
            cc_version = cc_version,
            flags = "-std=c11 -O2",
        },
        files = file_hashes,
        manifest = manifest,
        platform = platform,
        trampoline_hash = sign_ctx.trampoline_hash,
    }
    local payload = json.encode(payload_table)
    local sig_hex = crypto.ed25519_sign(payload, sk_hex)

    -- Write package.sig
    local sig_table = {
        binary_hash = sign_ctx.binary_hash,
        build = payload_table.build,
        files = file_hashes,
        manifest = manifest,
        platform = platform,
        trampoline_hash = sign_ctx.trampoline_hash,
        signature = sig_hex,
        public_key = pk_hex,
    }

    local pkg_sig = json.encode(sig_table)
    write_file(app_dir .. "/package.sig", pkg_sig .. "\n")
    print("wrote " .. app_dir .. "/package.sig")
end

local function main()
    local opts = parse_args()

    -- Find Lua files
    local lua_files = find_lua_files(opts.app_dir)
    if #lua_files == 0 then
        tool.stderr("hull build: no .lua files found in " .. opts.app_dir .. "\n")
        tool.exit(1)
    end

    print("hull build: " .. #lua_files .. " Lua file(s) from " .. opts.app_dir)

    -- Create temp directory
    local tmpdir = tool.tmpdir()

    -- Generate app_registry.c
    local registry_c = generate_app_registry(opts.app_dir, lua_files)
    write_file(tmpdir .. "/app_registry.c", registry_c)

    -- Generate template_registry.c (if templates/ dir exists)
    local templates_dir = opts.app_dir .. "/templates"
    local html_files = {}
    if file_exists(templates_dir) then
        html_files = find_html_files(templates_dir)
    end
    local template_registry_c = generate_template_registry(opts.app_dir, html_files)
    write_file(tmpdir .. "/template_registry.c", template_registry_c)
    if #html_files > 0 then
        print("hull build: " .. #html_files .. " template(s) from " .. templates_dir)
    end

    -- Generate static_registry.c (if static/ dir exists)
    local static_dir = opts.app_dir .. "/static"
    local static_files = {}
    if file_exists(static_dir) then
        static_files = find_all_files(static_dir)
    end
    local static_registry_c = generate_static_registry(opts.app_dir, static_files)
    write_file(tmpdir .. "/static_registry.c", static_registry_c)
    if #static_files > 0 then
        print("hull build: " .. #static_files .. " static file(s) from " .. static_dir)
    end

    -- Generate migration_registry.c (if migrations/ dir exists)
    local migrations_dir = opts.app_dir .. "/migrations"
    local migration_files = {}
    if file_exists(migrations_dir) then
        migration_files = find_sql_files(migrations_dir)
    end
    local migration_registry_c = generate_migration_registry(opts.app_dir, migration_files)
    write_file(tmpdir .. "/migration_registry.c", migration_registry_c)
    if #migration_files > 0 then
        print("hull build: " .. #migration_files .. " migration(s) from " .. migrations_dir)
    end

    -- Generate app_main.c
    local app_main = [[
extern int hull_main(int argc, char **argv);
int main(int argc, char **argv) { return hull_main(argc, argv); }
]]
    write_file(tmpdir .. "/app_main.c", app_main)

    -- Extract platform library (if embedded)
    local platform_extracted = false
    local platform_lib = tmpdir .. "/libhull_platform.a"

    -- Resolve CC early (needed for cosmo detection)
    local cc = opts.cc or tool.cc or "cosmocc"
    local is_cosmo = cc:find("cosmocc") ~= nil

    -- Try to find platform library in known locations
    -- 1. Check if build_assets has it embedded (multi-arch cosmo)
    if is_cosmo and tool.platform_archs then
        local archs = tool.platform_archs()
        if archs then
            local ok = tool.extract_platform_cosmo(tmpdir)
            if ok then
                platform_extracted = true
            end
        end
    end

    -- 1b. Single-arch embedded extraction
    if not platform_extracted and tool.extract_platform then
        local ok = tool.extract_platform(tmpdir)
        if ok and file_exists(platform_lib) then
            platform_extracted = true
        end
    end

    -- 2. Check build/ directory (development mode)
    local platform_dir = nil
    if not platform_extracted then
        -- Derive hull binary directory from __hull_exe global
        local hull_dir = ""
        if __hull_exe then
            hull_dir = __hull_exe:match("(.*/)" ) or ""
        end
        local dev_paths = {
            hull_dir,
            "build/",
            "../build/",
        }

        if is_cosmo then
            -- Look for multi-arch cosmo archives
            for _, d in ipairs(dev_paths) do
                local x86 = d .. "libhull_platform.x86_64-cosmo.a"
                local arm = d .. "libhull_platform.aarch64-cosmo.a"
                if file_exists(x86) and file_exists(arm) then
                    tool.copy(x86, tmpdir .. "/libhull_platform.a")
                    tool.mkdir(tmpdir .. "/.aarch64")
                    tool.copy(arm, tmpdir .. "/.aarch64/libhull_platform.a")
                    platform_dir = d
                    platform_extracted = true
                    break
                end
            end
            if not platform_extracted then
                -- Fallback: try single-arch archive (non-fat build)
                for _, d in ipairs(dev_paths) do
                    if file_exists(d .. "libhull_platform.a") then
                        tool.copy(d .. "libhull_platform.a", platform_lib)
                        platform_dir = d
                        platform_extracted = true
                        break
                    end
                end
            end
        else
            -- Single-arch fallback (unchanged)
            for _, d in ipairs(dev_paths) do
                if file_exists(d .. "libhull_platform.a") then
                    tool.copy(d .. "libhull_platform.a", platform_lib)
                    platform_dir = d
                    platform_extracted = true
                    break
                end
            end
        end
    end

    if not platform_extracted then
        if is_cosmo then
            tool.stderr("hull build: cannot find platform archives\n")
            tool.stderr("hint: run `make platform-cosmo` first\n")
        else
            tool.stderr("hull build: cannot find libhull_platform.a\n")
            tool.stderr("hint: run `make platform` first, or use an embedded hull build\n")
        end
        tool.rmdir(tmpdir)
        tool.exit(1)
    end

    -- Validate CC matches platform (cc already resolved above)
    if platform_dir then
        -- Validate: warn if user --cc doesn't match what platform was built with
        local cc_data = read_file(platform_dir .. "platform_cc")
        if cc_data and opts.cc then
            local platform_cc = cc_data:match("^%s*(.-)%s*$")
            if platform_cc ~= opts.cc then
                tool.stderr("hull build: warning: --cc " .. opts.cc ..
                    " does not match platform (built with " .. platform_cc .. ")\n")
            end
        end
    end

    -- Compile
    print("hull build: compiling...")
    local ok = tool.spawn({cc, "-std=c11", "-O2", "-w", "-c",
                           "-o", tmpdir .. "/app_registry.o",
                           tmpdir .. "/app_registry.c"})
    if not ok then
        tool.stderr("hull build: compilation failed (app_registry.c)\n")
        tool.rmdir(tmpdir)
        tool.exit(1)
    end

    ok = tool.spawn({cc, "-std=c11", "-O2", "-w", "-c",
                     "-o", tmpdir .. "/app_main.o",
                     tmpdir .. "/app_main.c"})
    if not ok then
        tool.stderr("hull build: compilation failed (app_main.c)\n")
        tool.rmdir(tmpdir)
        tool.exit(1)
    end

    ok = tool.spawn({cc, "-std=c11", "-O2", "-w", "-c",
                     "-o", tmpdir .. "/template_registry.o",
                     tmpdir .. "/template_registry.c"})
    if not ok then
        tool.stderr("hull build: compilation failed (template_registry.c)\n")
        tool.rmdir(tmpdir)
        tool.exit(1)
    end

    ok = tool.spawn({cc, "-std=c11", "-O2", "-w", "-c",
                     "-o", tmpdir .. "/static_registry.o",
                     tmpdir .. "/static_registry.c"})
    if not ok then
        tool.stderr("hull build: compilation failed (static_registry.c)\n")
        tool.rmdir(tmpdir)
        tool.exit(1)
    end

    ok = tool.spawn({cc, "-std=c11", "-O2", "-w", "-c",
                     "-o", tmpdir .. "/migration_registry.o",
                     tmpdir .. "/migration_registry.c"})
    if not ok then
        tool.stderr("hull build: compilation failed (migration_registry.c)\n")
        tool.rmdir(tmpdir)
        tool.exit(1)
    end

    -- Link
    print("hull build: linking...")
    local platform_a = tmpdir .. "/libhull_platform.a"
    ok = tool.spawn({cc, "-o", opts.output,
                     tmpdir .. "/app_main.o",
                     tmpdir .. "/app_registry.o",
                     tmpdir .. "/template_registry.o",
                     tmpdir .. "/static_registry.o",
                     tmpdir .. "/migration_registry.o",
                     platform_a,
                     "-lm", "-lpthread"})
    if not ok then
        tool.stderr("hull build: linking failed\n")
        tool.rmdir(tmpdir)
        tool.exit(1)
    end

    print("hull build: wrote " .. opts.output)

    -- Sign if requested
    if opts.sign then
        -- Find platform.sig alongside the platform library
        local platform_sig_path = nil
        if platform_dir then
            platform_sig_path = platform_dir .. "platform.sig"
        end
        -- Also check tmpdir (extracted embedded builds)
        if not platform_sig_path or not file_exists(platform_sig_path) then
            if file_exists(tmpdir .. "/platform.sig") then
                platform_sig_path = tmpdir .. "/platform.sig"
            end
        end
        -- Also check hull binary directory (embedded platform may not set platform_dir)
        if not platform_sig_path or not file_exists(platform_sig_path) then
            local hull_dir = ""
            if __hull_exe then
                hull_dir = __hull_exe:match("(.*/)" ) or ""
            end
            if hull_dir ~= "" and file_exists(hull_dir .. "platform.sig") then
                platform_sig_path = hull_dir .. "platform.sig"
            end
        end

        local sign_ctx = {
            cc = cc,
            binary_hash = nil,
            trampoline_hash = crypto.sha256(app_main),
            platform_sig_path = platform_sig_path,
        }

        -- Compute binary_hash (SHA256 of the linked output binary)
        local binary_data = read_file(opts.output)
        if binary_data then
            sign_ctx.binary_hash = crypto.sha256(binary_data)
        end

        sign_app(opts.app_dir, lua_files, opts.sign, sign_ctx, migration_files)
    end

    -- Cleanup
    tool.rmdir(tmpdir)
end

main()
